version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8232:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    container_name: app_nginx