version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8232:80"
    depends_on:
      - php
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  php:
    container_name: app_nginx
    image: php:8.0-fpm
    volumes:
      - ./:/var/www